### PR TITLE
Recommended Changes

### PR DESCRIPTION
**Pull request by JaydenDev**
- Remove deprecated center tag in favor of a centered div
- Use external CSS file
- Fixed indention of scratch.html (will work as normal)
^ these are the changes

### CODE REVIEW

**Comment by Chiroyce1** [comment]
The second one doesn't seem necessary...

**Comment by JaydenDev** [comment]
> The second one doesn't seem necessary...

Removing the "deprecated" <center> tag? It's deprecated, remove it!

**Comment by Chiroyce1** [comment]
> Use external CSS file

I meant this

**Comment by JaydenDev** [comment]
> > Use external CSS file
> 
> I meant this

It increases the ability to read the code. Plus 2 languages in one file messes up syntax highlighting and it annoys some. It's better to have seperate files, you get seen as a noob if you have in-html css

**Comment by Chiroyce1** [comment]
Well derter-menter doesn't seem like they're annoyed because of it.. but ok.

**Comment by JaydenDev** [comment]
> Well derter-menter doesn't seem like they're annoyed because of it.. but ok.

It's better to have seperate files. It makes syntax highlighting and fixing work properly. Makes the code more readable and more.

**Comment by JaydenDev** [comment]
If Derter-Menter doesn't want the external CSS file I can remake the PR with only the center tag removal commits. But I don't see why one wouldn't

**Comment by Chiroyce1** [comment]
Can you merge the border-radius PR?

**Comment by JaydenDev** [comment]
> Can you merge the border-radius PR?

ping them lol

**Comment by Chiroyce1** [comment]
> ping them lol

i meant [this](https://github.com/JaydenDev/derter-menter.github.io/pull/1)

**Comment by derter-menter** [comment]
> If Derter-Menter doesn't want the external CSS file I can remake the PR with only the center tag removal commits. But I don't see why one wouldn't

Yeah, for now I probably prefer every page I 1 file, it’s so I know what is all in a page

**Comment by derter-menter** [comment]
Actually, I see how it is done. Will merge, may revert if a change my mind

**Comment by derter-menter** [comment]
Reverted. It ruined the site completely

**Comment by JaydenDev** [comment]
> Reverted. It ruined the site completely

Could of been the centered div implementation, you can merge it and add the center tag back!

**Comment by JaydenDev** [comment]
It works when I use it idk?

**Comment by derter-menter** [comment]
> > Reverted. It ruined the site completely
> 
> Could of been the centered div implementation, you can merge it and add the center tag back!

Yeah the alignment got ruined

**Comment by JaydenDev** [comment]
> > > Reverted. It ruined the site completely
> > 
> > 
> > Could of been the centered div implementation, you can merge it and add the center tag back!
> 
> Yeah the alignment got ruined

I'll fix it later, you really should get rid of the deprecated <center> tag

**Comment by derter-menter** [comment]
> > > > Reverted. It ruined the site completely
> > > 
> > > 
> > > Could of been the centered div implementation, you can merge it and add the center tag back!
> > 
> > 
> > Yeah the alignment got ruined
> 
> I'll fix it later, you really should get rid of the deprecated center tag

It works on everything I have used

**Comment by JaydenDev** [comment]
> > > > > Reverted. It ruined the site completely
> > > > 
> > > > 
> > > > Could of been the centered div implementation, you can merge it and add the center tag back!
> > > 
> > > 
> > > Yeah the alignment got ruined
> > 
> > 
> > I'll fix it later, you really should get rid of the deprecated center tag
> 
> It works on everything I have used

The point is its deprecated, meaning at any time it can be removed. Do you want your app to randomly break at some point in time? It's also very unprofessional and should be replaced.

**Comment by derter-menter** [comment]
> > > > > > Reverted. It ruined the site completely
> > > > > 
> > > > > 
> > > > > Could of been the centered div implementation, you can merge it and add the center tag back!
> > > > 
> > > > 
> > > > Yeah the alignment got ruined
> > > 
> > > 
> > > I'll fix it later, you really should get rid of the deprecated center tag
> > 
> > 
> > It works on everything I have used
> 
> The point is its deprecated, meaning at any time it can be removed. Do you want your app to randomly break at some point in time? It's also very unprofessional and should be replaced.

Well, your solution broke my site completely, so I think I should stay with that for now

**Comment by JaydenDev** [comment]
> > > > > > > Reverted. It ruined the site completely
> > > > > > 
> > > > > > 
> > > > > > Could of been the centered div implementation, you can merge it and add the center tag back!
> > > > > 
> > > > > 
> > > > > Yeah the alignment got ruined
> > > > 
> > > > 
> > > > I'll fix it later, you really should get rid of the deprecated center tag
> > > 
> > > 
> > > It works on everything I have used
> > 
> > 
> > The point is its deprecated, meaning at any time it can be removed. Do you want your app to randomly break at some point in time? It's also very unprofessional and should be replaced.
> 
> Well, your solution broke my site completely, so I think I should stay with that for now

because I suck at centering div's

**Comment by Chiroyce1** [comment]
Calm down, I'll make a PR in about 2 hours centering the div.

**Comment by Chiroyce1** [comment]
PR made #15

**Comment by derter-menter** [comment]
> Calm down, I'll make a PR in about 2 hours centering the div.
> 
> Also @derter-menter I recommend locking this thread.

I would have done that long ago if I knew how to do it

**Comment by Chiroyce1** [comment]
Scroll up, on the right side, near this, you should see "Lock conversation"

image

**Pull request merged**
