### PR TITLE
Refactor HTML

### PR DESCRIPTION
**Pull request by Chiroyce1**
- Add a `<head>` tag
- Make sure `<body>`, `<head>` and `<html>` are all closed properly in the right order (it wasn't before)
- Add some `<meta>` tags to improve accessibility 
- Use `<p>` tags for text 
- Add a `<title>` tag
- Indentation is a must! Formatted code using Visual Studio Code

Tested, and it looks exactly the same as before
image

### CODE REVIEW

**Comment by Chiroyce1** [comment]
The links in the about section is still purple/blue - do you want that also to be white?

**Comment by derter-menter** [comment]
> The links in the about section is still purple/blue - do you want that also to be white?

Nah that is alright. Thanks for this, have no clue what a "meta" tag is but paragraph tags help. Yeah, I should close my tags lol. 

I see no issues so I will merge

**Comment by Chiroyce1** [comment]
> have no clue what a "meta" tag

The `<meta>` tag defines metadata about an HTML document. Metadata is data (information) about data.
[This](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta) should help more.

**Comment by derter-menter** [comment]
Just wanted to say I removed the meta tag as it actually made the site look worse on mobile

**Comment by Chiroyce1** [comment]
It did? Oh ok...

**Pull request merged**
