### PR TITLE
`<body>` tag is important

### PR DESCRIPTION
**Pull request by Chiroyce1**
even though it works - always best to use the proper tags.

### CODE REVIEW

**Comment by Chiroyce1** [comment]
DONT merge it yet - i have one more suggestion... one min..

**Comment by derter-menter** [comment]
I am editing right now so conflicts may happen

**Comment by Chiroyce1** [comment]
Tested, I changed the buttons so that you dont have to click on the text, only the button to go to the link. And I also did add the body tag, and fixed a bit of the css. Try merging now.

**Comment by derter-menter** [comment]
> Tested, I changed the buttons so that you dont have to click on the text, only the button to go to the link. And I also did add the body tag, and fixed a bit of the css. Try merging now.

Ight

**Pull request merged**
