### PR TITLE
Make sure to close the tags

### PR DESCRIPTION
**Pull request by Quantum-Codes**
I tested it on my fork, it looks the same. Changed 2 files

### CODE REVIEW

**Comment by Quantum-Codes** [comment]
BTW why do you have 2 branches?

**Comment by derter-menter** [comment]
Will merge, but why are body tags important?

**Comment by derter-menter** [comment]
> BTW why do you have 2 branches?

I should only have the "main"

**Comment by Quantum-Codes** [comment]
> Will merge, but why are body tags important?

Body tags aren't mandatory to put but it is a good practice to put it. It was mandatory before HTML5

Anything in the body tag is displayed in the page, it's easy to understand where the actual content started (while reading code) , looks organized and also body attributes `ALINK, VLINK, LINK, bgcolor` can be used

**Comment by Quantum-Codes** [comment]
> > BTW why do you have 2 branches?
> 
> I should only have the "main"

Ok

**Pull request merged**
