### PR TITLE
Link wasnt clear in dark mode

### PR DESCRIPTION
**Pull request by Quantum-Codes**
I changed it to be light blue.
Alink = active link (when u click, this color shows)
Vlink = visited link (when u already visited the site and see link again, it's this color)
link = unvisited link

Any questions then ask

### CODE REVIEW

**Comment by Chiroyce1** [comment]
Maybe add this to the `<style>` tag instead?

**Comment by Quantum-Codes** [comment]
> Maybe add this to the `<style>` tag instead?

Ok

**Comment by Quantum-Codes** [comment]
@Chiroyce1 do you know how to revert? :P

**Comment by Quantum-Codes** [comment]
Ok done. (I don't know how to revert lol)

a is the link tag and everything after the colons is sort of an event?

a:visited is same as Vlink
a:active is same as alink
a is same as link

**Comment by Quantum-Codes** [comment]
> Doesn't simply `a` work? I'm not sure though.

What I know is that:

- `a` is equivalent to `a:link`
- if u only change `a`, vlink and alink aren't changed. (I'm sure that alink doesn't change but I gotta test for vlink)

**Comment by Quantum-Codes** [comment]
@Chiroyce1 looks like u were right :P 
I just read this method from quora answer and it worked lol

Simply `a` works

**Pull request merged**
